travis:
  secure:
    BINSTAR_TOKEN: mxVv2g6zQcZXpXULExQCQa5JQVyaegK+p68FDHL9UcYHil3bxS5g3GI0b/CcQOlPiINzNivZ174sLiLrnkR9Nbw8/qy05Wznvw8/VKS1BnTFxm9RS6QJ5MqR84HGXtsxVPAqdHL2nOVDXqo8FvDu/++5TOSW3Ufv4SzEZoxrpxdpyInv3SxBAWyaXHO88JWfKyJdo7NpYacidtiWVCgsw/d60eKVokp5PNxVFSjZ16yXZqcOjGfU/N2xYzAkeTF/J0YHcJo1KvuQV/dc3h0/+/BENevM/Ry0J8tw5TGCADfgGrOB6aa2z7OWO6/1NVIlv66K3pdFmgnLTU89yuiXpTx7JtQnwBwHlxtx6lZtEFrjdugr9M1YRzrWf55/IwDmOneNR6OESjyzwFp7fA/avZ8RgzXa/I+BO8pkgxmMzxwT1YtGpxqVXsxWhy4TEMoBqNMzA9q7GGmUv0Oerffze8wUChocavT5rEs1ebxcE2d73KAC3xxrF+10FHp0V1IGbSJZVnGfudaHwlRAR2B+Stv75tAbeCMtQib7PjBNjYCmWxh5BTlo37BQ9eZq/Aswuo8obxpa9miFXik65F1fypXBPzUX46uWtcod1DSghip9Yo3OucSZ99N623sF9tP/5xXlntzdBKVROjgEgg4tRiX+PHyUOmLErZIwFcCeEZk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
